---
services: docker

env:
  - distro: centos-7

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  - ${PWD}/.travis/download-test-script.sh

  # Run tests.
  - ${PWD}/tests/test.sh
