---
services: docker

env:
  - distro: centos7

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/aidanns/a37ab5d09840253ef1d74218b3e739fb/raw/2dc8100bab92da745c7a7b38990df2a3546048d0/ansible-role-test.sh
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh
